import { setupI18n } from '@lingui/core';

import { messages as en } from './messages/en';
import { messages as fr } from './messages/fr';
import type { Locale } from './Routing';

// messages/{locale}.ts is generated by `lingui compile` and gitignored.
// setupI18n per locale rather than the global singleton: the prerender pass builds every locale
// in one Node process, and a shared instance switched with activate() races.
const CATALOGS = { en, fr } satisfies Record<Locale, unknown>;

export const getI18n = (locale: Locale) => setupI18n({ locale, messages: { [locale]: CATALOGS[locale] } });

export const getMessages = (locale: Locale) => CATALOGS[locale];
