import { setupI18n } from '@lingui/core';

import { messages as en } from './messages/en';
import { messages as fr } from './messages/fr';
import type { Locale } from './Routing';

/**
 * Compiled catalogues (`messages/{locale}.ts`, generated by `lingui compile`, git-ignored).
 * `setupI18n` per locale, not the global `i18n` singleton: the SSG pass pre-renders every locale
 * in the same Node process, so a shared instance switched with `activate()` races.
 */
const CATALOGS = { en, fr } satisfies Record<Locale, unknown>;

export const getI18n = (locale: Locale) => setupI18n({ locale, messages: { [locale]: CATALOGS[locale] } });

export const getMessages = (locale: Locale) => CATALOGS[locale];
