import { describe, expect, it, vi } from 'vitest';

const createRouter = vi.fn((options: Record<string, unknown>) => ({ options }));

vi.mock('@tanstack/react-router', () => ({ createRouter }));
// Generated by the TanStack plugin and gitignored, a unit test can't depend on it being there.
vi.mock('@/routeTree.gen', () => ({ routeTree: { id: '__root__' } }));

const { getRouter } = await import('@/router');

describe('getRouter', () => {
  it('should build a router from the generated route tree', () => {
    const router = getRouter();

    expect(createRouter).toHaveBeenCalledOnce();
    expect(router.options.routeTree).toEqual({ id: '__root__' });
  });

  it('should restore scroll position across navigations', () => {
    createRouter.mockClear();
    getRouter();

    // The canvas page has no scroll of its own, but the 404 and error pages do, and a back
    // navigation landing mid-page reads as a broken back button.
    expect(createRouter.mock.calls[0][0].scrollRestoration).toBe(true);
  });

  it('should preload on intent', () => {
    createRouter.mockClear();
    getRouter();

    expect(createRouter.mock.calls[0][0].defaultPreload).toBe('intent');
  });

  it('should return a fresh instance per call', () => {
    // The prerender renders every page in one Node process, and a shared router would carry one
    // page's location into the next.
    expect(getRouter()).not.toBe(getRouter());
  });
});
