import { msg } from '@lingui/core/macro';

import { getI18n } from '@/i18n/I18n';
import { LOCALE_TAGS, type Locale, alternateLanguages, localePath } from '@/i18n/Routing';
import { AUTHOR, SITE_TITLE, TWITTER_HANDLE } from '@/utils/config/Identity';
import { absoluteUrl } from '@/utils/config/Site';

const SITE_DESCRIPTION = msg`React + Vite + React Three Fiber starter.`;
const SOCIAL_PREVIEW_ALT = msg`React App Fondation — React + Vite + React Three Fiber starter.`;

// Regenerated by `pnpm assets:brand`. Keep the dimensions, some crawlers skip an image without.
const OG_IMAGE = { url: '/og-image.png', width: 1200, height: 630 };

// Mirrors --color-sky-top. Only `light` is emitted: the head dedupes by `name` and ignores
// `media`, so declaring both ships whichever came last.
export const THEME_COLOR = { light: '#c9dcf0', dark: '#0b1220' };

/**
 * A meta tag, since a static site has no server to set headers with. postbuild.mjs moves it after
 * <meta charset> because a meta policy only covers what follows it.
 *
 * 'unsafe-inline' is unavoidable: the router injects inline scripts during hydration and we have
 * no nonce. frame-ancestors is ignored here and upgrade-insecure-requests breaks WebKit on
 * localhost, so both belong at the edge with the real policy. This is the floor.
 */
export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  // wasm-unsafe-eval is for the Draco decoder.
  "script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'",
  "style-src 'self'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "connect-src 'self'",
  "worker-src 'self' blob:",
  "media-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'"
].join('; ');

type Tag = Record<string, string>;

export const rootHead = (): { meta: Tag[]; links: Tag[] } => ({
  meta: [
    { charSet: 'utf-8' },
    // httpEquiv and not http-equiv, React drops the HTML spelling and warns.
    { httpEquiv: 'Content-Security-Policy', content: CONTENT_SECURITY_POLICY },
    {
      name: 'viewport',
      // No maximum-scale/user-scalable=no, blocking pinch-zoom fails WCAG 1.4.4.
      content: 'width=device-width, initial-scale=1, minimum-scale=1, viewport-fit=cover'
    },
    { name: 'author', content: AUTHOR },
    { name: 'format-detection', content: 'telephone=no, address=no, email=no' },
    { name: 'mobile-web-app-capable', content: 'yes' },
    { name: 'apple-mobile-web-app-title', content: SITE_TITLE },
    { name: 'apple-mobile-web-app-status-bar-style', content: 'default' },
    { name: 'theme-color', content: THEME_COLOR.light }
  ],
  links: [
    { rel: 'icon', href: '/icons/favicon.svg', type: 'image/svg+xml' },
    { rel: 'icon', href: '/icons/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    { rel: 'apple-touch-icon', href: '/icons/apple-touch-icon.png', sizes: '180x180' },
    { rel: 'manifest', href: '/manifest.json' }
  ]
});

export const localeHead = (locale: Locale): { meta: Tag[]; links: Tag[] } => {
  const i18n = getI18n(locale);
  const description = i18n._(SITE_DESCRIPTION);
  const canonical = absoluteUrl(localePath(locale));
  const image = absoluteUrl(OG_IMAGE.url);

  return {
    meta: [
      { title: SITE_TITLE },
      { name: 'description', content: description },
      // No `keywords`: no search engine has read it since 2009 and it only ever goes stale.
      { name: 'robots', content: 'index, follow' },

      { property: 'og:type', content: 'website' },
      { property: 'og:url', content: canonical },
      { property: 'og:locale', content: LOCALE_TAGS[locale].replace('-', '_') },
      { property: 'og:site_name', content: SITE_TITLE },
      { property: 'og:title', content: SITE_TITLE },
      { property: 'og:description', content: description },
      { property: 'og:image', content: image },
      { property: 'og:image:width', content: String(OG_IMAGE.width) },
      { property: 'og:image:height', content: String(OG_IMAGE.height) },
      { property: 'og:image:alt', content: i18n._(SOCIAL_PREVIEW_ALT) },

      { name: 'twitter:card', content: 'summary_large_image' },
      ...(TWITTER_HANDLE ? [{ name: 'twitter:site', content: TWITTER_HANDLE }] : []),
      { name: 'twitter:title', content: SITE_TITLE },
      { name: 'twitter:description', content: description },
      { name: 'twitter:image', content: image }
    ],
    links: [
      { rel: 'canonical', href: canonical },
      // Without these the locales read as duplicate content instead of translations.
      ...Object.entries(alternateLanguages()).map(([tag, path]) => ({
        rel: 'alternate',
        hrefLang: tag,
        href: absoluteUrl(path)
      }))
    ]
  };
};
